spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/

zuul:
  routes:
    user-api:
      path: "/user-api/**"
      serviceId: eureka-producer






